-- ===========================================================================
-- P6 — THE DOUBLE-ENTRY LEDGER AND REFUNDS (specification 14, 17, 48)
--
-- Generated by drizzle-kit, then REVIEWED AND EDITED BY HAND. Four statements
-- were removed, along with a CREATE TABLE for payment_method_secrets, because
-- they re-proposed work that migrations 0013 and 0020
-- already did by hand — Drizzle does not read hand-written migrations, so it
-- believes the schema still lacks them. Applying them as generated would have
-- failed on a dropped constraint and a dropped column.
--
-- The machinery that makes this ledger trustworthy — the sum-to-zero rule,
-- the hash chain, append-only enforcement and row-level security — is in
-- migration 0025. It cannot be generated from a schema definition.
-- ===========================================================================

CREATE TYPE "public"."ledger_account_type" AS ENUM('ASSET', 'LIABILITY', 'INCOME', 'CONTRA_INCOME', 'EXPENSE');--> statement-breakpoint
CREATE TYPE "public"."ledger_normal_balance" AS ENUM('DEBIT', 'CREDIT');--> statement-breakpoint
CREATE TYPE "public"."ledger_transaction_kind" AS ENUM('SALE', 'REFUND', 'REFUND_PAYOUT', 'SETTLEMENT_PAYOUT', 'ADJUSTMENT');--> statement-breakpoint
CREATE TYPE "public"."refund_reason" AS ENUM('DUPLICATE_PAYMENT', 'CORRUPT_FILE', 'NOT_AS_DESCRIBED', 'PLATFORM_ERROR', 'OWNER_DISCRETION');--> statement-breakpoint
CREATE TYPE "public"."refund_status" AS ENUM('REQUESTED', 'APPROVED', 'REJECTED', 'PAID', 'WITHDRAWN');--> statement-breakpoint
CREATE TABLE "ledger_accounts" (
	"code" text PRIMARY KEY NOT NULL,
	"type" "ledger_account_type" NOT NULL,
	"normal_balance" "ledger_normal_balance" NOT NULL,
	"name_ar" text NOT NULL,
	"description_ar" text,
	"requires_contributor" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ledger_lines" (
	"seq" bigserial PRIMARY KEY NOT NULL,
	"transaction_id" uuid NOT NULL,
	"line_no" integer NOT NULL,
	"account_code" text NOT NULL,
	"contributor_id" uuid,
	"amount_minor" bigint NOT NULL,
	"currency" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"period_key" text NOT NULL,
	"kind" "ledger_transaction_kind" NOT NULL,
	"memo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ledger_transactions" (
	"seq" bigserial PRIMARY KEY NOT NULL,
	"id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"kind" "ledger_transaction_kind" NOT NULL,
	"currency" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"period_key" text NOT NULL,
	"reference_type" text NOT NULL,
	"reference_id" uuid,
	"memo" text,
	"actor_user_id" uuid,
	"prev_hash" text NOT NULL,
	"payload_hash" text NOT NULL,
	"entry_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refund_request_items" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"refund_request_id" uuid NOT NULL,
	"order_item_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"title_snapshot" text NOT NULL,
	"currency" text NOT NULL,
	"gross_minor" bigint NOT NULL,
	"engineer_amount_minor" bigint NOT NULL,
	"platform_amount_minor" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refund_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"order_id" uuid NOT NULL,
	"order_number" text NOT NULL,
	"customer_id" uuid NOT NULL,
	"status" "refund_status" DEFAULT 'REQUESTED' NOT NULL,
	"reason" "refund_reason" NOT NULL,
	"customer_note" text NOT NULL,
	"currency" text NOT NULL,
	"amount_minor" bigint NOT NULL,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"decided_by" uuid,
	"decided_at" timestamp with time zone,
	"decision_note" text,
	"reversal_transaction_id" uuid,
	"paid_at" timestamp with time zone,
	"payout_reference" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "refunded_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "refund_request_id" uuid;--> statement-breakpoint
-- Migration 0020 created this table with an inline REFERENCES clause, so the
-- constraint exists under PostgreSQL's auto-generated name. Renaming it keeps
-- one foreign key, matching the name Drizzle now expects; adding the generated
-- statement verbatim would leave two identical constraints on the same column.
ALTER TABLE "payment_method_secrets"
  RENAME CONSTRAINT "payment_method_secrets_payment_method_id_fkey"
  TO "payment_method_secrets_payment_method_id_payment_methods_id_fk";--> statement-breakpoint
ALTER TABLE "ledger_lines" ADD CONSTRAINT "ledger_lines_account_code_ledger_accounts_code_fk" FOREIGN KEY ("account_code") REFERENCES "public"."ledger_accounts"("code") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_lines" ADD CONSTRAINT "ledger_lines_contributor_id_contributors_id_fk" FOREIGN KEY ("contributor_id") REFERENCES "public"."contributors"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_request_items" ADD CONSTRAINT "refund_request_items_refund_request_id_refund_requests_id_fk" FOREIGN KEY ("refund_request_id") REFERENCES "public"."refund_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_request_items" ADD CONSTRAINT "refund_request_items_order_item_id_order_items_id_fk" FOREIGN KEY ("order_item_id") REFERENCES "public"."order_items"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_requests" ADD CONSTRAINT "refund_requests_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_requests" ADD CONSTRAINT "refund_requests_customer_id_users_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_lines_transaction_line_unique" ON "ledger_lines" USING btree ("transaction_id","line_no");--> statement-breakpoint
CREATE INDEX "ledger_lines_contributor_idx" ON "ledger_lines" USING btree ("contributor_id","currency","period_key");--> statement-breakpoint
CREATE INDEX "ledger_lines_account_idx" ON "ledger_lines" USING btree ("account_code","period_key","currency");--> statement-breakpoint
CREATE INDEX "ledger_lines_transaction_idx" ON "ledger_lines" USING btree ("transaction_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_transactions_id_unique" ON "ledger_transactions" USING btree ("id");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_transactions_entry_hash_unique" ON "ledger_transactions" USING btree ("entry_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_transactions_prev_hash_unique" ON "ledger_transactions" USING btree ("prev_hash");--> statement-breakpoint
CREATE INDEX "ledger_transactions_period_idx" ON "ledger_transactions" USING btree ("period_key","currency");--> statement-breakpoint
CREATE INDEX "ledger_transactions_reference_idx" ON "ledger_transactions" USING btree ("reference_type","reference_id");--> statement-breakpoint
CREATE INDEX "ledger_transactions_kind_idx" ON "ledger_transactions" USING btree ("kind","occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX "refund_request_items_unique" ON "refund_request_items" USING btree ("refund_request_id","order_item_id");--> statement-breakpoint
CREATE INDEX "refund_request_items_order_item_idx" ON "refund_request_items" USING btree ("order_item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "refund_requests_reference_unique" ON "refund_requests" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "refund_requests_order_idx" ON "refund_requests" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "refund_requests_customer_idx" ON "refund_requests" USING btree ("customer_id","requested_at");--> statement-breakpoint
CREATE INDEX "refund_requests_status_idx" ON "refund_requests" USING btree ("status","requested_at");