-- ===========================================================================
-- P7 — MONTHLY SETTLEMENT (specification 15, 16, 18 — decisions 8, 9)
--
-- Generated by drizzle-kit, then reviewed by hand. TWELVE statements were
-- removed because migrations 0025, 0026 and 0029 already applied them: Drizzle
-- does not read hand-written migrations, so it re-proposes their work on every
-- generate. Ten of them were `ALTER TYPE ... ADD VALUE` without IF NOT EXISTS,
-- which is the failure mode CLAUDE.md warns about — one duplicate label aborts
-- the WHOLE migration, so the new tables below would never have been created.
-- This generation finally records all of it in the snapshot.
--
-- The rules that make a settlement trustworthy — the lifecycle constraints,
-- the freeze after payment, and row-level security — are in migration 0032.
-- ===========================================================================

CREATE TYPE "public"."settlement_line_kind" AS ENUM('SALE', 'REFUND', 'ADJUSTMENT');--> statement-breakpoint
CREATE TYPE "public"."settlement_status" AS ENUM('PENDING', 'APPROVED', 'PAID', 'CARRIED_FORWARD', 'CANCELLED');--> statement-breakpoint
CREATE TABLE "settlement_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"settlement_id" uuid NOT NULL,
	"kind" "settlement_line_kind" NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"product_title" text NOT NULL,
	"currency" text NOT NULL,
	"gross_minor" bigint NOT NULL,
	"engineer_minor" bigint NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settlements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"contributor_id" uuid NOT NULL,
	"contributor_name" text,
	"settlement_code" text,
	"period_key" text NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end_exclusive" timestamp with time zone NOT NULL,
	"currency" text NOT NULL,
	"status" "settlement_status" DEFAULT 'PENDING' NOT NULL,
	"period_sales_minor" bigint NOT NULL,
	"period_refunds_minor" bigint NOT NULL,
	"period_adjustments_minor" bigint NOT NULL,
	"period_gross_sales_minor" bigint NOT NULL,
	"period_units_sold" integer DEFAULT 0 NOT NULL,
	"carried_forward_minor" bigint NOT NULL,
	"net_due_minor" bigint NOT NULL,
	"balance_minor" bigint NOT NULL,
	"minimum_payout_minor" bigint NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"generated_by" uuid,
	"approved_at" timestamp with time zone,
	"approved_by" uuid,
	"paid_at" timestamp with time zone,
	"paid_by" uuid,
	"payout_method" text,
	"payout_reference" text,
	"ledger_transaction_id" uuid,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "settlement_lines" ADD CONSTRAINT "settlement_lines_settlement_id_settlements_id_fk" FOREIGN KEY ("settlement_id") REFERENCES "public"."settlements"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "settlement_lines_settlement_idx" ON "settlement_lines" USING btree ("settlement_id","occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX "settlements_reference_unique" ON "settlements" USING btree ("reference");--> statement-breakpoint
CREATE UNIQUE INDEX "settlements_contributor_period_unique" ON "settlements" USING btree ("contributor_id","period_key","currency");--> statement-breakpoint
CREATE INDEX "settlements_period_idx" ON "settlements" USING btree ("period_key","status");--> statement-breakpoint
CREATE INDEX "settlements_contributor_idx" ON "settlements" USING btree ("contributor_id","period_key");--> statement-breakpoint
CREATE INDEX "settlements_status_idx" ON "settlements" USING btree ("status","generated_at");